name: CI
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18.0-beta1"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: ${{ matrix.go }}
      - run: go test -cover -race -v ./...
